services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbconsulting-api:
    build: .
    volumes: 
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db

volumes:
  postgres_data:
